#version: docker_verison

FROM python:3.6.8
WORKDIR ~/docker_version


COPY ./requirements.txt ./
RUN pip install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple
COPY . ./

CMD ["gunicorn", "start:app", "-c", "./gunicorn.conf.py"]